/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /**
         * Create Application
         * @description Manually add a job application.
         */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description Export filtered applications as CSV.
         */
        get: operations["export_csv_api_v1_applications_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_api_v1_applications__app_id__get"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_v1_applications__app_id__delete"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_v1_applications__app_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{app_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Status */
        patch: operations["update_status_api_v1_applications__app_id__status_patch"];
        trace?: never;
    };
    "/api/v1/analytics/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_v1_analytics_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/score-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Score Distribution */
        get: operations["get_score_distribution_api_v1_analytics_score_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendations */
        get: operations["get_recommendations_api_v1_analytics_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_v1_analytics_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Funnel */
        get: operations["get_funnel_api_v1_analytics_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/top-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top Companies */
        get: operations["get_top_companies_api_v1_analytics_top_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/company-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Types */
        get: operations["get_company_types_api_v1_analytics_company_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Search Run
         * @description Start a pipeline run. Returns immediately with a run_id for progress tracking.
         */
        post: operations["start_search_run_api_v1_search_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/runs/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Progress
         * @description SSE stream of pipeline progress messages.
         */
        get: operations["stream_run_progress_api_v1_search_runs__run_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/runs/{run_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Status
         * @description Poll-based fallback for run status.
         */
        get: operations["get_run_status_api_v1_search_runs__run_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description List recent pipeline runs.
         */
        get: operations["list_runs_api_v1_search_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Defaults
         * @description Return default search parameters from the active profile.
         */
        get: operations["get_search_defaults_api_v1_search_defaults_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Config
         * @description Get current LLM configuration and connection status.
         */
        get: operations["get_llm_config_api_v1_settings_llm_get"];
        /**
         * Update Llm Config
         * @description Update LLM provider configuration.
         */
        put: operations["update_llm_config_api_v1_settings_llm_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/llm/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Llm Connection
         * @description Test the current LLM connection.
         */
        post: operations["test_llm_connection_api_v1_settings_llm_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/llm/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Llm Presets
         * @description List available LLM provider presets.
         */
        get: operations["get_llm_presets_api_v1_settings_llm_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Database Info
         * @description Get database path, size, and record count.
         */
        get: operations["get_database_info_api_v1_settings_database_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List available search profiles.
         */
        get: operations["list_profiles_api_v1_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Get full config for a profile.
         */
        get: operations["get_profile_api_v1_profiles__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resume/{profile}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resume Status
         * @description Check if a resume exists for the given profile.
         */
        get: operations["get_resume_status_api_v1_resume__profile__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resume/{profile}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Resume
         * @description Upload a resume PDF for the given profile.
         */
        post: operations["upload_resume_api_v1_resume__profile__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resume/{profile}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Resume
         * @description Download the resume PDF for the given profile.
         */
        get: operations["download_resume_api_v1_resume__profile__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resume/{profile}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resume Text
         * @description Get parsed text content of the resume.
         */
        get: operations["get_resume_text_api_v1_resume__profile__text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Remote
             * @default false
             */
            is_remote: boolean;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /**
             * Status
             * @default found
             */
            status: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Profile
             * @default default
             */
            profile: string;
        };
        /** ApplicationListResponse */
        ApplicationListResponse: {
            /** Items */
            items: components["schemas"]["ApplicationResponse"][];
            /** Total */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Job Url
             * @default
             */
            job_url: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Is Remote
             * @default false
             */
            is_remote: boolean;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Id */
            id: number;
            /** Overall Score */
            overall_score?: number | null;
            /** Technical Score */
            technical_score?: number | null;
            /** Leadership Score */
            leadership_score?: number | null;
            /** Platform Building Score */
            platform_building_score?: number | null;
            /** Comp Potential Score */
            comp_potential_score?: number | null;
            /** Company Trajectory Score */
            company_trajectory_score?: number | null;
            /** Culture Fit Score */
            culture_fit_score?: number | null;
            /** Career Progression Score */
            career_progression_score?: number | null;
            /**
             * Recommendation
             * @default
             */
            recommendation: string;
            /**
             * Score Reasoning
             * @default
             */
            score_reasoning: string;
            /**
             * Key Strengths
             * @default []
             */
            key_strengths: string[];
            /**
             * Key Gaps
             * @default []
             */
            key_gaps: string[];
            /** Funding Stage */
            funding_stage?: string | null;
            /** Total Funding */
            total_funding?: string | null;
            /** Employee Count */
            employee_count?: string | null;
            /**
             * Company Type
             * @default
             */
            company_type: string;
            /**
             * Company Intel Json
             * @default
             */
            company_intel_json: string;
            /**
             * Resume Tweaks Json
             * @default
             */
            resume_tweaks_json: string;
            /**
             * Cover Letter
             * @default
             */
            cover_letter: string;
            /**
             * Application Method
             * @default
             */
            application_method: string;
            /**
             * Profile
             * @default default
             */
            profile: string;
            /**
             * Status
             * @default found
             */
            status: string;
            /** Date Found */
            date_found?: string | null;
            /** Date Applied */
            date_applied?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Contact Name
             * @default
             */
            contact_name: string;
            /**
             * Contact Email
             * @default
             */
            contact_email: string;
            /**
             * Referral Source
             * @default
             */
            referral_source: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Referral Source */
            referral_source?: string | null;
        };
        /** Body_upload_resume_api_v1_resume__profile__upload_post */
        Body_upload_resume_api_v1_resume__profile__upload_post: {
            /** File */
            file: string;
        };
        /** ChartDataPoint */
        ChartDataPoint: {
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Color */
            color?: string | null;
        };
        /** DashboardStats */
        DashboardStats: {
            /**
             * Total Jobs
             * @default 0
             */
            total_jobs: number;
            /** Avg Score */
            avg_score?: number | null;
            /**
             * Strong Apply Count
             * @default 0
             */
            strong_apply_count: number;
            /**
             * Apply Count
             * @default 0
             */
            apply_count: number;
            /**
             * Maybe Count
             * @default 0
             */
            maybe_count: number;
            /**
             * Skip Count
             * @default 0
             */
            skip_count: number;
            /**
             * Applied Count
             * @default 0
             */
            applied_count: number;
            /**
             * Interviewing Count
             * @default 0
             */
            interviewing_count: number;
            /**
             * Offer Count
             * @default 0
             */
            offer_count: number;
            /**
             * Response Rate
             * @default 0
             */
            response_rate: number;
        };
        /** DatabaseInfo */
        DatabaseInfo: {
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Size Mb
             * @default 0
             */
            size_mb: number;
            /**
             * Record Count
             * @default 0
             */
            record_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLMConfig */
        LLMConfig: {
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Model
             * @default
             */
            model: string;
        };
        /** LLMStatus */
        LLMStatus: {
            /**
             * Configured
             * @default false
             */
            configured: boolean;
            /**
             * Available
             * @default false
             */
            available: boolean;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /** LLMTestResult */
        LLMTestResult: {
            /** Success */
            success: boolean;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** ProfileDetail */
        ProfileDetail: {
            /** Name */
            name: string;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
        };
        /** ProfileSummary */
        ProfileSummary: {
            /** Name */
            name: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Target Roles Count
             * @default 0
             */
            target_roles_count: number;
            /**
             * Locations
             * @default []
             */
            locations: string[];
        };
        /** ProviderPreset */
        ProviderPreset: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /**
             * Needs Api Key
             * @default false
             */
            needs_api_key: boolean;
        };
        /** ResumeStatus */
        ResumeStatus: {
            /** Profile */
            profile: string;
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Path
             * @default
             */
            path: string;
        };
        /** ResumeUploadResponse */
        ResumeUploadResponse: {
            /** Profile */
            profile: string;
            /** Filename */
            filename: string;
            /**
             * Message
             * @default Resume uploaded successfully
             */
            message: string;
        };
        /** RunStatus */
        RunStatus: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Progress Messages */
            progress_messages?: string[];
            /**
             * Jobs Found
             * @default 0
             */
            jobs_found: number;
            /**
             * Jobs Scored
             * @default 0
             */
            jobs_scored: number;
            /** Error */
            error?: string | null;
        };
        /** SearchDefaults */
        SearchDefaults: {
            /** Roles */
            roles?: string[];
            /** Locations */
            locations?: string[];
            /** Keywords */
            keywords?: string[];
            /**
             * Max Days Old
             * @default 14
             */
            max_days_old: number;
            /**
             * Profile
             * @default default
             */
            profile: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Roles */
            roles?: string[];
            /** Locations */
            locations?: string[];
            /** Keywords */
            keywords?: string[];
            /**
             * Include Remote
             * @default true
             */
            include_remote: boolean;
            /**
             * Max Days Old
             * @default 14
             */
            max_days_old: number;
            /**
             * Use Ai
             * @default false
             */
            use_ai: boolean;
            /**
             * Profile
             * @default default
             */
            profile: string;
            /**
             * Mode
             * @description search_only | search_score | full_pipeline
             * @default search_score
             */
            mode: string;
        };
        /** StatusUpdate */
        StatusUpdate: {
            /** Status */
            status: string;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                status?: string | null;
                min_score?: number | null;
                recommendation?: string | null;
                source?: string | null;
                search?: string | null;
                company_type?: string | null;
                is_remote?: boolean | null;
                profile?: string | null;
                sort_by?: string;
                sort_dir?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_v1_applications_export_csv_get: {
        parameters: {
            query?: {
                status?: string | null;
                min_score?: number | null;
                recommendation?: string | null;
                source?: string | null;
                search?: string | null;
                company_type?: string | null;
                is_remote?: boolean | null;
                profile?: string | null;
                sort_by?: string;
                sort_dir?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_api_v1_applications__app_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__app_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__app_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_v1_applications__app_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_analytics_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    get_score_distribution_api_v1_analytics_score_distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDataPoint"][];
                };
            };
        };
    };
    get_recommendations_api_v1_analytics_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDataPoint"][];
                };
            };
        };
    };
    get_sources_api_v1_analytics_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDataPoint"][];
                };
            };
        };
    };
    get_funnel_api_v1_analytics_funnel_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartDataPoint"][];
                };
            };
        };
    };
    get_top_companies_api_v1_analytics_top_companies_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_types_api_v1_analytics_company_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_search_run_api_v1_search_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_progress_api_v1_search_runs__run_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_status_api_v1_search_runs__run_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_search_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_defaults_api_v1_search_defaults_get: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDefaults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_config_api_v1_settings_llm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatus"];
                };
            };
        };
    };
    update_llm_config_api_v1_settings_llm_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_connection_api_v1_settings_llm_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMTestResult"];
                };
            };
        };
    };
    get_llm_presets_api_v1_settings_llm_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPreset"][];
                };
            };
        };
    };
    get_database_info_api_v1_settings_database_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseInfo"];
                };
            };
        };
    };
    list_profiles_api_v1_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSummary"][];
                };
            };
        };
    };
    get_profile_api_v1_profiles__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_status_api_v1_resume__profile__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_v1_resume__profile__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_v1_resume__profile__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_resume_api_v1_resume__profile__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_text_api_v1_resume__profile__text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
