"""hosted public beta

Revision ID: a8877b7c16ec
Revises: 
Create Date: 2026-03-22 18:22:02.112599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8877b7c16ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('job_url', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('work_type', sa.String(length=20), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=16), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('salary_min_annualized', sa.Float(), nullable=True),
    sa.Column('salary_max_annualized', sa.Float(), nullable=True),
    sa.Column('estimated_total_comp', sa.String(length=200), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('leadership_score', sa.Float(), nullable=True),
    sa.Column('platform_building_score', sa.Float(), nullable=True),
    sa.Column('comp_potential_score', sa.Float(), nullable=True),
    sa.Column('company_trajectory_score', sa.Float(), nullable=True),
    sa.Column('culture_fit_score', sa.Float(), nullable=True),
    sa.Column('career_progression_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('key_strengths', sa.Text(), nullable=True),
    sa.Column('key_gaps', sa.Text(), nullable=True),
    sa.Column('funding_stage', sa.String(length=100), nullable=True),
    sa.Column('total_funding', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.String(length=100), nullable=True),
    sa.Column('company_intel_json', sa.Text(), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('resume_tweaks_json', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('application_method', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('search_run_id', sa.String(length=12), nullable=True),
    sa.Column('workspace_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_found', sa.DateTime(), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('date_response', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=300), nullable=True),
    sa.Column('contact_email', sa.String(length=300), nullable=True),
    sa.Column('referral_source', sa.String(length=300), nullable=True),
    sa.Column('url_status', sa.String(length=20), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_url')
    )
    op.create_index(op.f('ix_applications_workspace_id'), 'applications', ['workspace_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2000), nullable=True),
    sa.Column('auth_provider', sa.String(length=64), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_table('rate_limit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_name', sa.String(length=80), nullable=False),
    sa.Column('identity', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_events_bucket_name'), 'rate_limit_events', ['bucket_name'], unique=False)
    op.create_index(op.f('ix_rate_limit_events_created_at'), 'rate_limit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_events_identity'), 'rate_limit_events', ['identity'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('interval_hours', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_jobs_found', sa.Integer(), nullable=True),
    sa.Column('last_run_new_jobs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile')
    )
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('worker_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_heartbeats_last_seen_at'), 'worker_heartbeats', ['last_seen_at'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_workspaces_owner_user_id'), 'workspaces', ['owner_user_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('storage_provider', sa.String(length=32), nullable=True),
    sa.Column('bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=2000), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_owner_user_id'), 'file_assets', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_file_assets_workspace_id'), 'file_assets', ['workspace_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('period_key', sa.String(length=64), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('limit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_counters_metric'), 'usage_counters', ['metric'], unique=False)
    op.create_index(op.f('ix_usage_counters_period_key'), 'usage_counters', ['period_key'], unique=False)
    op.create_index(op.f('ix_usage_counters_workspace_id'), 'usage_counters', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.create_table('workspace_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('roles_json', sa.Text(), nullable=True),
    sa.Column('keywords_json', sa.Text(), nullable=True),
    sa.Column('preferred_places_json', sa.Text(), nullable=True),
    sa.Column('workplace_preference', sa.String(length=32), nullable=True),
    sa.Column('max_days_old', sa.Integer(), nullable=True),
    sa.Column('current_title', sa.String(length=300), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_base_url', sa.String(length=500), nullable=True),
    sa.Column('llm_api_key', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('current_comp', sa.Float(), nullable=True),
    sa.Column('compensation_currency', sa.String(length=8), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('min_base', sa.Float(), nullable=True),
    sa.Column('target_total_comp', sa.Float(), nullable=True),
    sa.Column('min_acceptable_tc', sa.Float(), nullable=True),
    sa.Column('include_equity', sa.Boolean(), nullable=True),
    sa.Column('exclude_staffing_agencies', sa.Boolean(), nullable=True),
    sa.Column('include_remote', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_preferences_workspace_id'), 'workspace_preferences', ['workspace_id'], unique=True)
    op.create_table('workspace_search_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_search_events_created_at'), 'workspace_search_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_search_events_run_id'), 'workspace_search_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_workspace_search_events_workspace_id'), 'workspace_search_events', ['workspace_id'], unique=False)
    op.create_table('workspace_search_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_scored', sa.Integer(), nullable=True),
    sa.Column('strong_matches', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_search_runs_available_at'), 'workspace_search_runs', ['available_at'], unique=False)
    op.create_index(op.f('ix_workspace_search_runs_run_id'), 'workspace_search_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_workspace_search_runs_workspace_id'), 'workspace_search_runs', ['workspace_id'], unique=False)
    op.create_table('workspace_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_sessions_session_token_hash'), 'workspace_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_workspace_sessions_workspace_id'), 'workspace_sessions', ['workspace_id'], unique=False)
    op.create_table('workspace_resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('file_asset_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=2000), nullable=True),
    sa.Column('text_path', sa.String(length=2000), nullable=True),
    sa.Column('storage_provider', sa.String(length=32), nullable=True),
    sa.Column('storage_path', sa.String(length=2000), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=True),
    sa.Column('parse_warning', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_assets.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_resumes_workspace_id'), 'workspace_resumes', ['workspace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_resumes_workspace_id'), table_name='workspace_resumes')
    op.drop_table('workspace_resumes')
    op.drop_index(op.f('ix_workspace_sessions_workspace_id'), table_name='workspace_sessions')
    op.drop_index(op.f('ix_workspace_sessions_session_token_hash'), table_name='workspace_sessions')
    op.drop_table('workspace_sessions')
    op.drop_index(op.f('ix_workspace_search_runs_workspace_id'), table_name='workspace_search_runs')
    op.drop_index(op.f('ix_workspace_search_runs_run_id'), table_name='workspace_search_runs')
    op.drop_index(op.f('ix_workspace_search_runs_available_at'), table_name='workspace_search_runs')
    op.drop_table('workspace_search_runs')
    op.drop_index(op.f('ix_workspace_search_events_workspace_id'), table_name='workspace_search_events')
    op.drop_index(op.f('ix_workspace_search_events_run_id'), table_name='workspace_search_events')
    op.drop_index(op.f('ix_workspace_search_events_created_at'), table_name='workspace_search_events')
    op.drop_table('workspace_search_events')
    op.drop_index(op.f('ix_workspace_preferences_workspace_id'), table_name='workspace_preferences')
    op.drop_table('workspace_preferences')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_usage_counters_workspace_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_period_key'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_metric'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_file_assets_workspace_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_owner_user_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_workspaces_owner_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_worker_heartbeats_last_seen_at'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_rate_limit_events_identity'), table_name='rate_limit_events')
    op.drop_index(op.f('ix_rate_limit_events_created_at'), table_name='rate_limit_events')
    op.drop_index(op.f('ix_rate_limit_events_bucket_name'), table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_applications_workspace_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
