export type LocationKind = 'city' | 'country' | 'region';

export interface LocationOption {
  label: string;
  kind: LocationKind;
  country?: string;
  region?: string;
  aliases?: string[];
}

const COUNTRIES: LocationOption[] = [
  { label: 'United States', kind: 'country', aliases: ['USA', 'US', 'United States of America', 'America'] },
  { label: 'Canada', kind: 'country' },
  { label: 'Mexico', kind: 'country' },
  { label: 'Brazil', kind: 'country' },
  { label: 'Argentina', kind: 'country' },
  { label: 'Chile', kind: 'country' },
  { label: 'Colombia', kind: 'country' },
  { label: 'Peru', kind: 'country' },
  { label: 'Costa Rica', kind: 'country' },
  { label: 'United Kingdom', kind: 'country', aliases: ['UK', 'Britain', 'Great Britain'] },
  { label: 'Ireland', kind: 'country' },
  { label: 'Germany', kind: 'country' },
  { label: 'France', kind: 'country' },
  { label: 'Spain', kind: 'country' },
  { label: 'Portugal', kind: 'country' },
  { label: 'Italy', kind: 'country' },
  { label: 'Netherlands', kind: 'country' },
  { label: 'Belgium', kind: 'country' },
  { label: 'Switzerland', kind: 'country' },
  { label: 'Austria', kind: 'country' },
  { label: 'Sweden', kind: 'country' },
  { label: 'Norway', kind: 'country' },
  { label: 'Denmark', kind: 'country' },
  { label: 'Finland', kind: 'country' },
  { label: 'Poland', kind: 'country' },
  { label: 'Czech Republic', kind: 'country', aliases: ['Czechia'] },
  { label: 'Hungary', kind: 'country' },
  { label: 'Romania', kind: 'country' },
  { label: 'Turkey', kind: 'country', aliases: ['Turkiye'] },
  { label: 'United Arab Emirates', kind: 'country', aliases: ['UAE'] },
  { label: 'Saudi Arabia', kind: 'country' },
  { label: 'Israel', kind: 'country' },
  { label: 'South Africa', kind: 'country' },
  { label: 'Nigeria', kind: 'country' },
  { label: 'Kenya', kind: 'country' },
  { label: 'Egypt', kind: 'country' },
  { label: 'India', kind: 'country' },
  { label: 'Pakistan', kind: 'country' },
  { label: 'Bangladesh', kind: 'country' },
  { label: 'Sri Lanka', kind: 'country' },
  { label: 'Nepal', kind: 'country' },
  { label: 'Singapore', kind: 'country' },
  { label: 'Malaysia', kind: 'country' },
  { label: 'Indonesia', kind: 'country' },
  { label: 'Philippines', kind: 'country' },
  { label: 'Thailand', kind: 'country' },
  { label: 'Vietnam', kind: 'country' },
  { label: 'Taiwan', kind: 'country' },
  { label: 'South Korea', kind: 'country', aliases: ['Korea'] },
  { label: 'Japan', kind: 'country' },
  { label: 'China', kind: 'country' },
  { label: 'Hong Kong', kind: 'country' },
  { label: 'Australia', kind: 'country' },
  { label: 'New Zealand', kind: 'country' },
];

const REGIONS: LocationOption[] = [
  { label: 'California, United States', kind: 'region', country: 'United States', aliases: ['California', 'CA'] },
  { label: 'New York, United States', kind: 'region', country: 'United States', aliases: ['New York State', 'NY'] },
  { label: 'Texas, United States', kind: 'region', country: 'United States', aliases: ['Texas', 'TX'] },
  { label: 'Ontario, Canada', kind: 'region', country: 'Canada', aliases: ['Ontario'] },
  { label: 'British Columbia, Canada', kind: 'region', country: 'Canada', aliases: ['British Columbia', 'BC'] },
  { label: 'Quebec, Canada', kind: 'region', country: 'Canada', aliases: ['Quebec'] },
  { label: 'England, United Kingdom', kind: 'region', country: 'United Kingdom', aliases: ['England'] },
  { label: 'Scotland, United Kingdom', kind: 'region', country: 'United Kingdom', aliases: ['Scotland'] },
  { label: 'Bavaria, Germany', kind: 'region', country: 'Germany', aliases: ['Bavaria'] },
  { label: 'Catalonia, Spain', kind: 'region', country: 'Spain', aliases: ['Catalonia'] },
  { label: 'New South Wales, Australia', kind: 'region', country: 'Australia', aliases: ['New South Wales', 'NSW'] },
  { label: 'Victoria, Australia', kind: 'region', country: 'Australia', aliases: ['Victoria'] },
  { label: 'Maharashtra, India', kind: 'region', country: 'India', aliases: ['Maharashtra'] },
  { label: 'Karnataka, India', kind: 'region', country: 'India', aliases: ['Karnataka'] },
];

const CITIES: LocationOption[] = [
  { label: 'New York, NY', kind: 'city', country: 'United States', region: 'New York', aliases: ['New York City', 'NYC', 'Manhattan, NY', 'Brooklyn, NY'] },
  { label: 'San Francisco, CA', kind: 'city', country: 'United States', region: 'California', aliases: ['SF', 'San Francisco Bay Area'] },
  { label: 'Los Angeles, CA', kind: 'city', country: 'United States', region: 'California', aliases: ['LA', 'Los Angeles'] },
  { label: 'Chicago, IL', kind: 'city', country: 'United States', region: 'Illinois' },
  { label: 'Seattle, WA', kind: 'city', country: 'United States', region: 'Washington' },
  { label: 'Boston, MA', kind: 'city', country: 'United States', region: 'Massachusetts' },
  { label: 'Austin, TX', kind: 'city', country: 'United States', region: 'Texas' },
  { label: 'Washington, DC', kind: 'city', country: 'United States', region: 'District of Columbia', aliases: ['Washington DC', 'DC'] },
  { label: 'Atlanta, GA', kind: 'city', country: 'United States', region: 'Georgia' },
  { label: 'Denver, CO', kind: 'city', country: 'United States', region: 'Colorado' },
  { label: 'Miami, FL', kind: 'city', country: 'United States', region: 'Florida' },
  { label: 'San Diego, CA', kind: 'city', country: 'United States', region: 'California' },
  { label: 'Portland, OR', kind: 'city', country: 'United States', region: 'Oregon' },
  { label: 'Philadelphia, PA', kind: 'city', country: 'United States', region: 'Pennsylvania' },
  { label: 'Dallas, TX', kind: 'city', country: 'United States', region: 'Texas' },
  { label: 'Houston, TX', kind: 'city', country: 'United States', region: 'Texas' },
  { label: 'Phoenix, AZ', kind: 'city', country: 'United States', region: 'Arizona' },
  { label: 'Raleigh, NC', kind: 'city', country: 'United States', region: 'North Carolina' },
  { label: 'Nashville, TN', kind: 'city', country: 'United States', region: 'Tennessee' },
  { label: 'Minneapolis, MN', kind: 'city', country: 'United States', region: 'Minnesota' },
  { label: 'Toronto, Canada', kind: 'city', country: 'Canada', region: 'Ontario' },
  { label: 'Vancouver, Canada', kind: 'city', country: 'Canada', region: 'British Columbia' },
  { label: 'Montreal, Canada', kind: 'city', country: 'Canada', region: 'Quebec' },
  { label: 'Mexico City, Mexico', kind: 'city', country: 'Mexico' },
  { label: 'Guadalajara, Mexico', kind: 'city', country: 'Mexico' },
  { label: 'Sao Paulo, Brazil', kind: 'city', country: 'Brazil', aliases: ['Sao Paulo', 'Sao Paolo'] },
  { label: 'Rio de Janeiro, Brazil', kind: 'city', country: 'Brazil' },
  { label: 'Buenos Aires, Argentina', kind: 'city', country: 'Argentina' },
  { label: 'Santiago, Chile', kind: 'city', country: 'Chile' },
  { label: 'Bogota, Colombia', kind: 'city', country: 'Colombia', aliases: ['Bogota'] },
  { label: 'Lima, Peru', kind: 'city', country: 'Peru' },
  { label: 'San Jose, Costa Rica', kind: 'city', country: 'Costa Rica' },
  { label: 'London, United Kingdom', kind: 'city', country: 'United Kingdom', region: 'England' },
  { label: 'Manchester, United Kingdom', kind: 'city', country: 'United Kingdom', region: 'England' },
  { label: 'Edinburgh, United Kingdom', kind: 'city', country: 'United Kingdom', region: 'Scotland' },
  { label: 'Dublin, Ireland', kind: 'city', country: 'Ireland' },
  { label: 'Berlin, Germany', kind: 'city', country: 'Germany' },
  { label: 'Munich, Germany', kind: 'city', country: 'Germany', aliases: ['Munchen, Germany'] },
  { label: 'Frankfurt, Germany', kind: 'city', country: 'Germany' },
  { label: 'Paris, France', kind: 'city', country: 'France' },
  { label: 'Madrid, Spain', kind: 'city', country: 'Spain' },
  { label: 'Barcelona, Spain', kind: 'city', country: 'Spain', region: 'Catalonia' },
  { label: 'Lisbon, Portugal', kind: 'city', country: 'Portugal' },
  { label: 'Porto, Portugal', kind: 'city', country: 'Portugal' },
  { label: 'Amsterdam, Netherlands', kind: 'city', country: 'Netherlands' },
  { label: 'Brussels, Belgium', kind: 'city', country: 'Belgium' },
  { label: 'Zurich, Switzerland', kind: 'city', country: 'Switzerland' },
  { label: 'Vienna, Austria', kind: 'city', country: 'Austria' },
  { label: 'Stockholm, Sweden', kind: 'city', country: 'Sweden' },
  { label: 'Oslo, Norway', kind: 'city', country: 'Norway' },
  { label: 'Copenhagen, Denmark', kind: 'city', country: 'Denmark' },
  { label: 'Helsinki, Finland', kind: 'city', country: 'Finland' },
  { label: 'Warsaw, Poland', kind: 'city', country: 'Poland' },
  { label: 'Prague, Czech Republic', kind: 'city', country: 'Czech Republic' },
  { label: 'Budapest, Hungary', kind: 'city', country: 'Hungary' },
  { label: 'Bucharest, Romania', kind: 'city', country: 'Romania' },
  { label: 'Istanbul, Turkey', kind: 'city', country: 'Turkey' },
  { label: 'Dubai, United Arab Emirates', kind: 'city', country: 'United Arab Emirates', aliases: ['Dubai, UAE'] },
  { label: 'Abu Dhabi, United Arab Emirates', kind: 'city', country: 'United Arab Emirates', aliases: ['Abu Dhabi, UAE'] },
  { label: 'Tel Aviv, Israel', kind: 'city', country: 'Israel', aliases: ['Tel Aviv-Yafo, Israel'] },
  { label: 'Johannesburg, South Africa', kind: 'city', country: 'South Africa' },
  { label: 'Cape Town, South Africa', kind: 'city', country: 'South Africa' },
  { label: 'Lagos, Nigeria', kind: 'city', country: 'Nigeria' },
  { label: 'Nairobi, Kenya', kind: 'city', country: 'Kenya' },
  { label: 'Cairo, Egypt', kind: 'city', country: 'Egypt' },
  { label: 'Bengaluru, India', kind: 'city', country: 'India', region: 'Karnataka', aliases: ['Bangalore, India', 'Bangalore'] },
  { label: 'Hyderabad, India', kind: 'city', country: 'India' },
  { label: 'Mumbai, India', kind: 'city', country: 'India', region: 'Maharashtra' },
  { label: 'Delhi, India', kind: 'city', country: 'India', aliases: ['New Delhi, India', 'New Delhi'] },
  { label: 'Pune, India', kind: 'city', country: 'India', region: 'Maharashtra' },
  { label: 'Chennai, India', kind: 'city', country: 'India' },
  { label: 'Karachi, Pakistan', kind: 'city', country: 'Pakistan' },
  { label: 'Dhaka, Bangladesh', kind: 'city', country: 'Bangladesh' },
  { label: 'Colombo, Sri Lanka', kind: 'city', country: 'Sri Lanka' },
  { label: 'Kathmandu, Nepal', kind: 'city', country: 'Nepal' },
  { label: 'Singapore', kind: 'city', country: 'Singapore' },
  { label: 'Kuala Lumpur, Malaysia', kind: 'city', country: 'Malaysia' },
  { label: 'Jakarta, Indonesia', kind: 'city', country: 'Indonesia' },
  { label: 'Manila, Philippines', kind: 'city', country: 'Philippines' },
  { label: 'Bangkok, Thailand', kind: 'city', country: 'Thailand' },
  { label: 'Ho Chi Minh City, Vietnam', kind: 'city', country: 'Vietnam', aliases: ['Ho Chi Minh, Vietnam', 'Saigon, Vietnam', 'Saigon'] },
  { label: 'Hanoi, Vietnam', kind: 'city', country: 'Vietnam' },
  { label: 'Taipei, Taiwan', kind: 'city', country: 'Taiwan' },
  { label: 'Seoul, South Korea', kind: 'city', country: 'South Korea' },
  { label: 'Tokyo, Japan', kind: 'city', country: 'Japan' },
  { label: 'Osaka, Japan', kind: 'city', country: 'Japan' },
  { label: 'Beijing, China', kind: 'city', country: 'China' },
  { label: 'Shanghai, China', kind: 'city', country: 'China' },
  { label: 'Shenzhen, China', kind: 'city', country: 'China' },
  { label: 'Hong Kong', kind: 'city', country: 'Hong Kong' },
  { label: 'Sydney, Australia', kind: 'city', country: 'Australia', region: 'New South Wales' },
  { label: 'Melbourne, Australia', kind: 'city', country: 'Australia', region: 'Victoria' },
  { label: 'Brisbane, Australia', kind: 'city', country: 'Australia' },
  { label: 'Auckland, New Zealand', kind: 'city', country: 'New Zealand' },
  { label: 'Wellington, New Zealand', kind: 'city', country: 'New Zealand' },
];

export const LOCATION_OPTIONS: LocationOption[] = [
  ...CITIES,
  ...REGIONS,
  ...COUNTRIES,
];
